name: examples
permissions:
  contents: read

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      
  workflow_dispatch:
    
  schedule:
    - cron: '25 12 * * *'   # once a day @ 12:25pm UTC (5:35am PST)

jobs:
  AppKit:
    name: AppKit
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
    
    - name: Endpoint Menus - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/AppKit/Endpoint Menus/Endpoint Menus.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Endpoint Menus - Build
      run: xcodebuild build -project "Examples/AppKit/Endpoint Menus/Endpoint Menus.xcodeproj" -scheme "Endpoint Menus" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

    - name: Event Parsing - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/AppKit/Event Parsing/Event Parsing.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Event Parsing - Build
      run: xcodebuild build -project "Examples/AppKit/Event Parsing/Event Parsing.xcodeproj" -scheme "Event Parsing" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

    - name: Virtual Input - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/AppKit/Virtual Input/Virtual Input.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Virtual Input - Build
      run: xcodebuild build -project "Examples/AppKit/Virtual Input/Virtual Input.xcodeproj" -scheme "Virtual Input" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

    - name: Virtual Output - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/AppKit/Virtual Output/Virtual Output.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Virtual Output - Build
      run: xcodebuild build -project "Examples/AppKit/Virtual Output/Virtual Output.xcodeproj" -scheme "Virtual Output" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
  
  SwiftUI-iOS:
    name: SwiftUI iOS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
    - name: Bootstrap Platforms
      # Workaround for Xcode/GitHub runner issues finding simulators.
      # see https://github.com/actions/runner-images/issues/12758#issuecomment-3206748945
      run: xcrun simctl list
    - name: Download Platform(s)
      # Workaround for Xcode/GitHub runner issues finding simulators.
      # see https://github.com/actions/runner-images/issues/12758#issuecomment-3206748945
      run: xcodebuild -downloadPlatform iOS

    - name: Bluetooth MIDI - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/SwiftUI iOS/Bluetooth MIDI/Bluetooth MIDI.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Bluetooth MIDI - Build # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/SwiftUI iOS/Bluetooth MIDI/Bluetooth MIDI.xcodeproj" -scheme "Bluetooth MIDI" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

    - name: USB iOS to Mac - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/SwiftUI iOS/USB iOS to Mac/USB iOS to Mac.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: USB iOS to Mac - Build # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/SwiftUI iOS/USB iOS to Mac/USB iOS to Mac.xcodeproj" -scheme "USB iOS to Mac" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

  SwiftUI-Multiplatform:
    name: SwiftUI Multiplatform
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
    - name: Bootstrap Platforms
      # Workaround for Xcode/GitHub runner issues finding simulators.
      # see https://github.com/actions/runner-images/issues/12758#issuecomment-3206748945
      run: xcrun simctl list
    - name: Download Platform(s)
      # Workaround for Xcode/GitHub runner issues finding simulators.
      # see https://github.com/actions/runner-images/issues/12758#issuecomment-3206748945
      run: xcodebuild -downloadPlatform iOS

    - name: AsyncStream Devices and Endpoints - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/SwiftUI Multiplatform/AsyncStream Devices and Endpoints/AsyncStream Devices and Endpoints.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: AsyncStream Devices and Endpoints - Build (iOS) # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/AsyncStream Devices and Endpoints/AsyncStream Devices and Endpoints.xcodeproj" -scheme "AsyncStream Devices and Endpoints" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: AsyncStream Devices and Endpoints - Build (macOS)
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/AsyncStream Devices and Endpoints/AsyncStream Devices and Endpoints.xcodeproj" -scheme "AsyncStream Devices and Endpoints" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    
    - name: Event Parsing - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/SwiftUI Multiplatform/Event Parsing/Event Parsing.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Event Parsing - Build (iOS) # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/Event Parsing/Event Parsing.xcodeproj" -scheme "Event Parsing" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Event Parsing - Build (macOS)
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/Event Parsing/Event Parsing.xcodeproj" -scheme "Event Parsing" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
      
    - name: MIDI System Info - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/SwiftUI Multiplatform/MIDI System Info/MIDI System Info.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: MIDI System Info - Build (iOS) # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/MIDI System Info/MIDI System Info.xcodeproj" -scheme "MIDI System Info iOS" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: MIDI System Info - Build (macOS)
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/MIDI System Info/MIDI System Info.xcodeproj" -scheme "MIDI System Info macOS" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    
    - name: Observable Manager - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/SwiftUI Multiplatform/Observable Manager/Observable Manager.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Observable Manager - Build (iOS) # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/Observable Manager/Observable Manager.xcodeproj" -scheme "Observable Manager" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Observable Manager - Build (macOS)
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/Observable Manager/Observable Manager.xcodeproj" -scheme "Observable Manager" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    
    - name: ObservableObject Manager - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/SwiftUI Multiplatform/ObservableObject Manager/ObservableObject Manager.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: ObservableObject Manager - Build (iOS) # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/ObservableObject Manager/ObservableObject Manager.xcodeproj" -scheme "ObservableObject Manager" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: ObservableObject Manager - Build (macOS)
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/ObservableObject Manager/ObservableObject Manager.xcodeproj" -scheme "ObservableObject Manager" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    
    - name: System Notifications - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/SwiftUI Multiplatform/System Notifications/System Notifications.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: System Notifications - Build (iOS) # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/System Notifications/System Notifications.xcodeproj" -scheme "System Notifications" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: System Notifications - Build (macOS)
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/System Notifications/System Notifications.xcodeproj" -scheme "System Notifications" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

    - name: Virtual Input - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/SwiftUI Multiplatform/Virtual Input/Virtual Input.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Virtual Input - Build (iOS) # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/Virtual Input/Virtual Input.xcodeproj" -scheme "Virtual Input" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Virtual Input - Build (macOS)
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/Virtual Input/Virtual Input.xcodeproj" -scheme "Virtual Input" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

    - name: Virtual Output - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/SwiftUI Multiplatform/Virtual Output/Virtual Output.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Virtual Output - Build (iOS) # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/Virtual Output/Virtual Output.xcodeproj" -scheme "Virtual Output" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Virtual Output - Build (macOS)
      run: xcodebuild build -project "Examples/SwiftUI Multiplatform/Virtual Output/Virtual Output.xcodeproj" -scheme "Virtual Output" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

  UIKit:
    name: UIKit
    runs-on: macos-latest
    timeout-minutes: 40
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable # Sometimes a newer version of Xcode is available but isn't yet made default
    - name: Bootstrap Platforms
      # Workaround for Xcode/GitHub runner issues finding simulators.
      # see https://github.com/actions/runner-images/issues/12758#issuecomment-3206748945
      run: xcrun simctl list
    - name: Download Platform(s)
      # Workaround for Xcode/GitHub runner issues finding simulators.
      # see https://github.com/actions/runner-images/issues/12758#issuecomment-3206748945
      run: xcodebuild -downloadPlatform iOS
      
    - name: Bluetooth MIDI - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/UIKit/Bluetooth MIDI/Bluetooth MIDI.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Bluetooth MIDI - Build # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/UIKit/Bluetooth MIDI/Bluetooth MIDI.xcodeproj" -scheme "Bluetooth MIDI" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    
    - name: Event Parsing - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/UIKit/Event Parsing/Event Parsing.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Event Parsing - Build # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/UIKit/Event Parsing/Event Parsing.xcodeproj" -scheme "Event Parsing" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

    - name: Virtual Input - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/UIKit/Virtual Input/Virtual Input.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Virtual Input - Build # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/UIKit/Virtual Input/Virtual Input.xcodeproj" -scheme "Virtual Input" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

    - name: Virtual Output - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Examples/UIKit/Virtual Output/Virtual Output.xcodeproj" -resolvePackageDependencies | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Virtual Output - Build # by targeting a simulator device, we bypass requiring a Developer Team ID
      run: xcodebuild build -project "Examples/UIKit/Virtual Output/Virtual Output.xcodeproj" -scheme "Virtual Output" -destination "generic/platform=iOS Simulator,name=Any iOS Simulator Device" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
